remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: Somewhenever — Storytelling, Somewhen
description: A year long series of storytelling events planned for 2023 on the Isle of Wight.
